### ISSUE TITLE
Know Issues/TODO

### ISSUE THREAD

**Issue by evandrocoan** [evandroforks/AppointmentPublishing#1]
1. [ ] Complete the TODO on https://github.com/evandroforks/AppointmentPublishing#todo
1. [ ] Create user management/control with user names on HTTP header (and may also employ OAuth 2.0?)
   Accordingly to the SQL tables created by **`com.appointment.publishing.model`** classes,
   the user relation between them can be created by:
   1. Creating new tables relating each user between the existing tables (which is bad for performance, but has no data duplication). Is bad for performance because it will be required to consult 2 tables on the database, before actually getting the required data.
   1. Update the existing tables to include direct user relations (which is good for performance, but has data duplication). It will be good for performance because it will require only a single table on the database, before getter the required data.
1. [ ] Fix a POST request used multiple times creating multiple publications, i.e., when then they contain the same data
1. [ ] Employ Docker and GitHub Actions with PostgreSQL as a database backend
1. [ ] Perform stress/load tests using some tool as Apache JMeter and identify the server throughputs
